artifactory_contextUrl=https://labkey.jfrog.io/artifactory

artifactoryPluginVersion=6.0.4

commonsIoVersion=2.22.0
commonsLang3Version=3.20.0
commonsTextVersion=1.15.0

grgitGradleVersion=5.3.3
graphqlJavaVersion=26.1

groovySqlVersion=5.1.2

httpclient5Version=5.6.3
httpcore5Version=5.4.3

jacksonVersion=2.21.6
jsonVersion=20260814
