artifactory_contextUrl=https://labkey.jfrog.io/artifactory

artifactoryPluginVersion=6.0.4

commonsIoVersion=2.21.0
commonsLang3Version=3.20.0
commonsTextVersion=1.15.0

grgitGradleVersion=5.3.3
graphqlJavaVersion=25.0

groovySqlVersion=5.0.4

httpclient5Version=5.6
httpcore5Version=5.4.2

jacksonVersion=2.21.2
jsonVersion=20251224
