artifactory_contextUrl=https://labkey.jfrog.io/artifactory

artifactoryPluginVersion=5.2.5

commonsIoVersion=2.18.0
commonsLang3Version=3.17.0
commonsTextVersion=1.13.0

grgitGradleVersion=5.3.0
graphqlJavaVersion=22.3

httpclientVersion=5.4.1
httpcoreVersion=5.3.1

jacksonVersion=2.18.2
jsonVersion=20240303
